-- Community collaboration: group governance, user safety and notification routing.
alter table public.community_group_members
  drop constraint if exists community_group_members_role_check;
update public.community_group_members set role = 'owner' where role = 'admin';
alter table public.community_group_members
  alter column role set default 'member';
alter table public.community_group_members
  add constraint community_group_members_role_check check (role in ('owner', 'moderator', 'member'));

alter table public.community_events_calendar
  add column if not exists group_id bigint references public.community_groups(id) on delete set null,
  add column if not exists meeting_url text;

alter table public.community_notifications
  add column if not exists target_url text,
  add column if not exists read_at timestamptz;

create table if not exists public.community_user_blocks (
  id bigint generated by default as identity primary key,
  blocker_user_id uuid not null references auth.users(id) on delete cascade,
  blocked_user_id uuid not null references auth.users(id) on delete cascade,
  blocked_profile_id uuid references public.community_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blocker_user_id, blocked_user_id),
  check (blocker_user_id <> blocked_user_id)
);
create index if not exists community_user_blocks_blocked_idx
  on public.community_user_blocks (blocked_user_id, blocker_user_id);
alter table public.community_user_blocks enable row level security;
drop policy if exists "community_user_blocks_own" on public.community_user_blocks;
create policy "community_user_blocks_own" on public.community_user_blocks
  for all to authenticated
  using (auth.uid() = blocker_user_id)
  with check (auth.uid() = blocker_user_id);

drop policy if exists "community_group_members_manage" on public.community_group_members;
create policy "community_group_members_manage" on public.community_group_members
  for update to authenticated
  using (
    public.is_admin() or exists (
      select 1 from public.community_group_members manager
      where manager.group_id = community_group_members.group_id
        and manager.user_id = auth.uid() and manager.role = 'owner'
    )
  );
